/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TrackingImport } from './routes/tracking'
import { Route as ServicesImport } from './routes/services'
import { Route as ScheduleDeliveryImport } from './routes/schedule-delivery'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as AppDriverDashboardImport } from './routes/app/driver/dashboard'
import { Route as AppCustomerDashboardImport } from './routes/app/customer/dashboard'

// Create/Update Routes

const TrackingRoute = TrackingImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRoute,
} as any)

const ServicesRoute = ServicesImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const ScheduleDeliveryRoute = ScheduleDeliveryImport.update({
  id: '/schedule-delivery',
  path: '/schedule-delivery',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppDriverDashboardRoute = AppDriverDashboardImport.update({
  id: '/app/driver/dashboard',
  path: '/app/driver/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AppCustomerDashboardRoute = AppCustomerDashboardImport.update({
  id: '/app/customer/dashboard',
  path: '/app/customer/dashboard',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/schedule-delivery': {
      id: '/schedule-delivery'
      path: '/schedule-delivery'
      fullPath: '/schedule-delivery'
      preLoaderRoute: typeof ScheduleDeliveryImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesImport
      parentRoute: typeof rootRoute
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingImport
      parentRoute: typeof rootRoute
    }
    '/app/customer/dashboard': {
      id: '/app/customer/dashboard'
      path: '/app/customer/dashboard'
      fullPath: '/app/customer/dashboard'
      preLoaderRoute: typeof AppCustomerDashboardImport
      parentRoute: typeof rootRoute
    }
    '/app/driver/dashboard': {
      id: '/app/driver/dashboard'
      path: '/app/driver/dashboard'
      fullPath: '/app/driver/dashboard'
      preLoaderRoute: typeof AppDriverDashboardImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/schedule-delivery': typeof ScheduleDeliveryRoute
  '/services': typeof ServicesRoute
  '/tracking': typeof TrackingRoute
  '/app/customer/dashboard': typeof AppCustomerDashboardRoute
  '/app/driver/dashboard': typeof AppDriverDashboardRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/schedule-delivery': typeof ScheduleDeliveryRoute
  '/services': typeof ServicesRoute
  '/tracking': typeof TrackingRoute
  '/app/customer/dashboard': typeof AppCustomerDashboardRoute
  '/app/driver/dashboard': typeof AppDriverDashboardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/schedule-delivery': typeof ScheduleDeliveryRoute
  '/services': typeof ServicesRoute
  '/tracking': typeof TrackingRoute
  '/app/customer/dashboard': typeof AppCustomerDashboardRoute
  '/app/driver/dashboard': typeof AppDriverDashboardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/schedule-delivery'
    | '/services'
    | '/tracking'
    | '/app/customer/dashboard'
    | '/app/driver/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/schedule-delivery'
    | '/services'
    | '/tracking'
    | '/app/customer/dashboard'
    | '/app/driver/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/schedule-delivery'
    | '/services'
    | '/tracking'
    | '/app/customer/dashboard'
    | '/app/driver/dashboard'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ScheduleDeliveryRoute: typeof ScheduleDeliveryRoute
  ServicesRoute: typeof ServicesRoute
  TrackingRoute: typeof TrackingRoute
  AppCustomerDashboardRoute: typeof AppCustomerDashboardRoute
  AppDriverDashboardRoute: typeof AppDriverDashboardRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ScheduleDeliveryRoute: ScheduleDeliveryRoute,
  ServicesRoute: ServicesRoute,
  TrackingRoute: TrackingRoute,
  AppCustomerDashboardRoute: AppCustomerDashboardRoute,
  AppDriverDashboardRoute: AppDriverDashboardRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/contact",
        "/schedule-delivery",
        "/services",
        "/tracking",
        "/app/customer/dashboard",
        "/app/driver/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/schedule-delivery": {
      "filePath": "schedule-delivery.tsx"
    },
    "/services": {
      "filePath": "services.tsx"
    },
    "/tracking": {
      "filePath": "tracking.tsx"
    },
    "/app/customer/dashboard": {
      "filePath": "app/customer/dashboard.tsx"
    },
    "/app/driver/dashboard": {
      "filePath": "app/driver/dashboard.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
