# This workflow deploys the cloud functions to Firebase on manual dispatch.

name: "[DEV] Deploy Cloud Functions"
on:
  push:
    branches:
      - main
    paths:
      - backends/functions/**
      - common/**
      - .github/workflows/dev-deploy-cloud-functions.yml

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./backends/functions

env:
  BUN_VERSION: 1.2.4
  FIREBASE_PROJECT_ID: freedman-trucking-dev

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - run: bun i --frozen-lockfile

      # Download the latest firebase tools.
      - run: bun add -g firebase-tools

      # Setup credentials for Firebase and Google Cloud tools.
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FREEDMAN_TRUCKING_DEV }}"

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.FIREBASE_PROJECT_ID }}

      # Create .env file.
      - run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY_DEV }}" > .env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY_DEV }}" >> .env
          echo "STRIPE_WEBHOOK_SECRET_SELF_ACCOUNT=${{ secrets.STRIPE_WEBHOOK_SECRET_SELF_ACCOUNT_DEV }}" >> .env
          echo "STRIPE_WEBHOOK_SECRET_CONNECTED_ACCOUNT=${{ secrets.STRIPE_WEBHOOK_SECRET_CONNECTED_ACCOUNT_DEV }}" >> .env

      # Deploy Cloud Functions.
      # The double --force is not a mistake — the second one applies to artifact policy setup.
      - run: >
          firebase deploy --force --project "${{ env.FIREBASE_PROJECT_ID }}" 
          --only functions 
          -m "Deployment of cloud functions to dev environment"
          --force
