name: "[PROD] Deploy Remote Configs"
on:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  BUN_VERSION: 1.2.4
  NODE_VERSION: 22.*
  WORK_FLOW_FILE_NAME: prod-deploy-remote-config

defaults:
  run:
    working-directory: ./backends/remote-configs

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ env.WORK_FLOW_FILE_NAME }}
          filters: |
            src:
              - '.github/workflows/prod-deploy-remote-config.yml'
              - 'backends/remote-configs/**'

  lint-remote-config:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Install pre-requisites.
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - run: bun i --frozen-lockfile
      - run: bun lint

  deploy-remote-config:
    needs: lint-remote-config
    if: ${{ needs.lint-remote-config.result == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - run: bun i --frozen-lockfile

      # Setup credentials for Firebase and Google Cloud tools.
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FREEDMEN_S_TRUCKING }}"

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: freedmen-s-trucking

      # Deploy Firebase Remote Config settings.
      - run: bun deploy.ts --environment=prod

      # Update workflow base tag.
      - name: Update tag to current commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag -f "$TAG_NAME"
          git push origin -f "$TAG_NAME"
        env:
          TAG_NAME: ${{ env.WORK_FLOW_FILE_NAME }}
