name: "[PROD] Deploy Firebase Hosting"
on:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  WORK_FLOW_FILE_NAME: prod-deploy-firebase-hosting

defaults:
  run:
    working-directory: webapp

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      # True if changes are detected or tag does not exist.
      changeDetected: ${{ steps.filter.outputs.src == 'true' || steps.tag_check.outputs.exists == 'false' }}
    steps:
      - uses: actions/checkout@v4
      - name: Check if tag exists
        id: tag_check
        run: |
          TAG_NAME="${{ env.WORK_FLOW_FILE_NAME }}"
          if git ls-remote --tags origin "refs/tags/$TAG_NAME" | grep "$TAG_NAME" > /dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - uses: dorny/paths-filter@v3
        id: filter
        if: steps.tag_check.outputs.exists == 'true'
        with:
          base: ${{ env.WORK_FLOW_FILE_NAME }}
          filters: |
            src:
              - '.github/workflows/prod-deploy-firebase-hosting.yml'
              - 'webapp/**'
              - 'common/**'

  build_and_deploy_prod:
    needs: changes
    if: ${{ needs.changes.outputs.changeDetected }}
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun i --frozen-lockfile && bun run build
        env:
          VITE_AUTHENTICATE_DOT_COM_TOKEN: ${{ secrets.AUTHENTICATE_DOT_COM_TOKEN_PROD }}
          VITE_FIREBASE_CONFIG_JSON: ${{ secrets.FIREBASE_CONFIG_JSON_PROD }}
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY_PROD }}
          VITE_STRIPE_CLIENT_SECRET: ${{ secrets.STRIPE_CLIENT_SECRET_PROD }}
          VITE_PUBLIC_WEBAPP_URL: ${{ vars.PUBLIC_WEBAPP_URL_PROD }}
          VITE_SERVER_API_ENDPOINT: ${{ vars.SERVER_API_ENDPOINT_PROD }}
          VITE_APP_ENV: prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FREEDMEN_S_TRUCKING }}
          channelId: live
          projectId: freedmen-s-trucking

  update-tag:
    needs: build_and_deploy_prod
    if: ${{ needs.build_and_deploy_prod.result == 'success' }}
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Update workflow base tag.
      - name: Update tag to current commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag -f "$TAG_NAME"
          git push origin -f "$TAG_NAME"
        env:
          TAG_NAME: ${{ env.WORK_FLOW_FILE_NAME }}
